#
# Run "make all" to create example executables.
# 11/02/2013

all:
	g++ -Wall  schunk_hinfinitycontrol_example.cpp ../DQ.cpp ../DQ_kinematics.cpp ../controllers/HInfinityRobustController.cpp -o schunk_hinfinitycontrol_example
clean:
	rm -f schunk_hinfinitycontrol_example

