name: CPP Build Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testbranches: ['release','master']

    steps:
      - uses: actions/checkout@v2

      - name: apt update
        run: sudo apt update
        
      - name: Install pre-requisites
        run: sh .github/scripts/ubuntu/install_prerequisites.sh
          
      - name: Build
        run: sh .github/scripts/ubuntu/build.sh
        
      - name: Install
        run: sh .github/scripts/ubuntu/install.sh
          
      - name: Download examples ((${{ matrix.testbranches }}))
        run: git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp-examples.git
        
      - name: Build pure examples
        run: |
          cd cpp-examples
          chmod +x .build_pure.sh
          ./.build_pure.sh
          
